### ISSUE TITLE
If it can be done reliably, the script should also determine the disk's power consumption

### ISSUE THREAD

**Issue by thomas-profitt** [TheRemote/PiBenchmarks#1]
Hi!

I think you're doing something great working towards getting hard numbers on SBC disk performance and making the measurements available -- there's not a lot of transparency from the industry around this at all, and this needs to be done.

One other metric that's important in some SBC usecases is power consumption -- a HDD consumes more power than an SSD, but by how much? An SSD consumes more power than a micro SD card (right?), but by how much?

Is there a way to reliably determine how much power consumption increases during disk operations, and compare this between disks, to determine the disks' efficiencies, and whether there are any differences?

**Comment by TheRemote** [comment]
Hey Thomas,

I wish this were possible!  Unfortunately I believe the only way to measure this is using a multimeter or kill-a-watt or other hardware measurement device.

There are some laptops that track more advanced power consumption but it doesn't seem like any of this is available to us on the Pi.

If anyone has any way to do this let me know as I would love to add it, but as far as I know it can't be done!
