### ISSUE TITLE
website hard to search and a few comments on the site.

### ISSUE THREAD

**Issue by bsimmo** [TheRemote/PiBenchmarks#12]
Are there any improvements due for you benchmark website?
I send up data, but then cannot search for my nickname to get the results.
I cannot search for a specific drive, mainly as there is no search function.

SCORE in the Top List etc are not clickable to get actual information (or average information) from it.

Headers are not sortable.

and a big *please*
Can we have _Portable SSD_ moved in to SSD
I ask this as you cannot find a pendrive now, it's useless.

Portable SSD are identical to the normal SSD , it's just they come with the adaptor and in a case, there is no different since all go through USB, so all are portable.

That would tidy it up a bit and make the website useful.

**Comment by TheRemote** [comment]
Hey bsimmo,

I did end up doing a lot of these things.  The sortable headers are a possibility but you're able to drill down on the site now as well as it having a real search function (both for models and results).

Thanks for the feedback, I honestly appreciate it!
