### ISSUE TITLE
Pi4 : VLI and EEPROM detection

### ISSUE THREAD

**Issue by bsimmo** [TheRemote/PiBenchmarks#13]
It would be nice to add
VLI (so USB firmware) detection
EEPROM (do main boot firmware) detection.

Just to add two things that may alter USB and Pi performance.

(while here, possibly kernel version too)

**Comment by TheRemote** [comment]
Hmmm, those are pretty good ideas!  So the good news I think I already have everything I need to do this.  The EEPROM one is the only one I'm not positive I have the data for somewhere that just needs to be parsed and displayed.  I will see if I can get these implemented in the near future here!
