### ISSUE TITLE
Please, add PiBenchmarks to Home Assistant like Addon (in Hass OS)

### ISSUE THREAD

**Issue by vencakratky** [TheRemote/PiBenchmarks#19]
I tried via Putty/Terminal  `sudo curl https://raw.githubusercontent.com/TheRemote/PiBenchmarks/master/Storage.sh | sudo bash`
but after running test error 
![Pibench](https://user-images.githubusercontent.com/54419577/114887442-be9fc200-9e08-11eb-9dd5-8615d81822b7.jpg)
The problem is probably with unsupported "Home Assistant OS 5.13" on Raspberry 4
It is possible to create an addon directly ?
Thank you

**Comment by TheRemote** [comment]
Strange, I will definitely investigate this and see if I can get a fix for Home Assistant.  I know some people have submitted benchmarks successfully from there but they may be installing the dependencies like fio or iozone some other way.

I should be able to figure out what is going wrong if I download a copy of HomeAssistant and give it a run!

**Comment by TheRemote** [comment]
I think we have this working thanks to mhaas!
