### ISSUE TITLE
128Gb Netac sdcard showing as 32Gb Hama sdcard

### ISSUE THREAD

**Issue by paulwratt** [TheRemote/PiBenchmarks#20]
I have a 128Gb Netac (blue) sdcard that came with a rear-view mirror camera kit that I got on AliExpress. Both parts of the kit are legit and work fine. In fact I am impressed enough with the sdcard to get 5 more (@20$US when on special).

I just ran the speedtest and it is trying to tell me my sdcard is a 32Gb Hama sdscard, which it is not:

https://pibenchmarks.com/benchmark/55239

Actually that page says its a 96GB capacity (so maybe the picture is misleading, but why?), well this is what the local system tells me:

```
mmcblk0     179:0    0 116.5G  0 disk 
├─mmcblk0p1 179:1    0   3.9G  0 part /boot
├─mmcblk0p2 179:2    0  96.7G  0 part /
└─mmcblk0p3 179:3    0    16G  0 part 
```

Whats going on, something does not add up here. Is Netac really going to rebadge an sdcard?

FYI: Netac is a _HUGE_ producer of sdcards in China, but most of their sdcards (advertising seems to) target non-computer related products, like cameras, etc (as opposed to say being used as boot medium for a SBC like RPi)

Cheers

Paul
EDIT: I still have the packaging for the sdcard somewhere

**Comment by TheRemote** [comment]
Hey Paul,

Yes, I have seen entries like this in the past and they are very puzzling.  Some of them were for sure confirmed to be fakes later.

One of the easiest ways to see if that space is "real" is to try filling it up by just copying some files.  Probably something like:

cat /dev/urandom > test

and let it run for a bit and generate some garbage in a file.  If the drive is fake things will go off the rails once you run out of "real" space.  If that is real, addressable space then it will fill all the way up if you let it.  

I have got some 1TB flash drives using this same trick as well.  They would show the full 1TB capacity but once you filled it past 20-30% or so it would start throwing errors and crash out.

There's also a Google Play store app that can scan the card and try to determine if it's genuine.  There's an article with this linked at the bottom here:  https://www.phonearena.com/news/Beware-of-fake-microSD-cards-Heres-how-to-tell-a-counterfeit-from-the-original_id77769.

It may be worth looking at the packaging.  That link actually covers some of the things to look for in the coloring of the logos and common signs that it's counterfeit.  If it's fake it's most likely the seller/store and not Netac behind it.  

TP-Link also has some really good info on what to look for here as well as a PC utility if plugging the SD card in the PC for a scan is easier than the phone:  https://www.tp-link.com/us/support/faq/2592/

The brand may still be getting selected wrong but let's investigate this first as it's usually not a good sign to see a partition table like that with a capacity way larger than even the card's printed values.  Definitely let us know what you find when you take a closer look!

**Comment by paulwratt** [comment]
I was really really impressed with this cardd, enough to want to get another 4/5 of them, when they are on special @20$ (or less).

Its definitely _not_ a 32GB SD card, it has 50Gb of data on it now, and the 10Gb swap partition has been maxed out once, so there is 60Gb. I have physically seen a USB Flash drive that was bogus, and there are ways to check (as you point out) and this is not one of them (I use this SD-Card as boot device everyday for over 15 months now, no problems, and regularly build and pudate various large git projects with it, again, without problems).

I will try an order some more of them (I just have other priorities most of the time). When I get them I'll post back here.
