### ISSUE TITLE
Arch: the results are never shown

### ISSUE THREAD

**Issue by pschmitt** [TheRemote/PiBenchmarks#3]
```
curl https://raw.githubusercontent.com/TheRemote/PiBenchmarks/master/Storage.sh | sudo bash
[...]
RandRead: 6985 - RandWrite: 1998 - Read: 6806 - Write: 2026
Enter a description of your storage (SSD vs SD card, made by SanDisk, anything relevant:
Description: zsh: done                   curl  | 
zsh: suspended (tty input)  sudo bash

**Comment by pschmitt** [comment]
This is actually the result of `iozone` not being installed on my system. After installing it manually it works.

**Comment by TheRemote** [comment]
Hey pschmitt,

Thanks for your PR!  You already diagnosed it accurately as if the test is incomplete it is stored on the server and flagged (for me to review why the tests couldn't be run) but never shown publicly.  

I accepted your PR, thanks a ton!
