### ISSUE TITLE
eMMC storage doesn't seem to show up

### ISSUE THREAD

**Issue by terrorpup** [TheRemote/PiBenchmarks#30]
Hi, for the last few days I been running the bench mark on Orange Pi's 256 GB eMMC, and none of the test are showing up. I have ran the test on both Raxda Rock 5A and Indiedroid-Nova. I have notice that there not a lot of eMMC showing up.

**Comment by TheRemote** [comment]
Are they showing now?  I've added a few new eMMC card IDs to the storage database.  Can you see if those results are now displaying?

**Comment by terrorpup** [comment]
I will look shortly, I think they were, I will let you know
