### ISSUE TITLE
Benchmarks submitted and accepted by form are not displayed

### ISSUE THREAD

**Issue by arekm** [TheRemote/PiBenchmarks#33]
One of my submissions (probably 74857 or 74858) was accepted by form php script but is not showing up on the page.

Looking at other submission numbers there are tons of holes (aka submitted but missing on the web page results). I guess the problem comes from some server side data not added for drives ? (https://github.com/TheRemote/PiBenchmarks/issues/9). Product links or something?

Could such results still be still shown, without missing data obviously? (when missing server side data gets added then it would show full data info).

API shows no content for these...
````

% curl -k -L https://pibenchmarks.com/api/benchmark/74857| jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   252  100   252    0     0    915      0 --:--:-- --:--:-- --:--:--   929
100    86    0    86    0     0    170      0 --:--:-- --:--:-- --:--:--     0
{
  "result": [
    "benchmark",
    "74857",
    ""
  ],
  "response_code": 204,
  "response_desc": "No Content 1"
}
% curl -k -L https://pibenchmarks.com/api/benchmark/74858| jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   252  100   252    0     0    723      0 --:--:-- --:--:-- --:--:--   730
100    86    0    86    0     0    149      0 --:--:-- --:--:-- --:--:--   149
{
  "result": [
    "benchmark",
    "74858",
    ""
  ],
  "response_code": 204,
  "response_desc": "No Content 1"
}
````

**Comment by FingerlessGlov3s** [comment]
I've submitted a few benchmarks on my Pi5 and it's been days with no sign of them on the website, but I can see there's benchmarks on the website from today. Not sure what's happening there.

**Comment by arekm** [comment]
You didn't mention if storage.sh actually told you that the data was submitted (it should via "Result submitted successfully and will appear live on https://pibenchmarks.com within a couple of minutes." message).

If it did but no results on web page the you came to correct issue.

If it didn't then try adding export LC_ALL=C at beginning of storage.sh script and your problem is most likely different issue than this. Probably https://github.com/TheRemote/PiBenchmarks/issues/32.

**Comment by FingerlessGlov3s** [comment]
Adding `export LC_ALL=C` fixed the issue for me 🙂.

I have my locale set for `en_GB.UTF-8` could that be the issue? 🤔

**Comment by TheRemote** [comment]
Thank you all for reporting this.  I've added export LC_ALL=C to the top of storage.sh to prevent this in the future.  Thanks again!

**Comment by arekm** [comment]
But this issue was mainly about "Could such results still be still shown, without missing data obviously? (when missing server side data gets added then it would show full data info)." ...

**Comment by TheRemote** [comment]
They are for missing boards.  They aren't for missing storage devices right now mostly to keep it from being spammed with a bunch of blank image templates or really messed up/corrupted benchmarks.

This may change going forward but it hasn't really been a very big issue.  It only happens if you're the first one *ever* to test a device on the site basically.

I hadn't done updates for a few months (the longest I've ever gone without doing them) and there were a few dozen new storage devices.  I'm guessing the reason these posts started appearing is I just haven't been adding them as fast.  It has worked this way for at least 4+ years though but if I keep getting behind I may indeed change that!

**Comment by technolhodgy** [comment]
I have been trying to submit benchmarks and it seems to be failing.

I added 2 lines to locale 'Storage.sh'
else
   echo "Submission failed!"
   
So I only ever seen the "Submission failed!"

my attempts are 
https://www.amazon.co.uk/gp/product/B09L7WD411?th=1
https://www.amazon.co.uk/gp/product/B091BG4HDW?th=1

using the prototype the same as https://pibenchmarks.com/user/pimoroni/
I have tried use my broadband and mobile tethering for internet connection to eliminated any reasons for fail at my end.

**Comment by arekm** [comment]
Add set -x at beginning of the script and see what is returned from server.

**Comment by technolhodgy** [comment]
Failed query in <b>FormTools\Submissions, /var/www/storage/formtools/global/code/Submissions.class.php</b>, line 204, error: SQLSTATE[HY000]: General error: 3988 Conversion from collation utf8mb3_general_ci into utf8mb4_bin impossible for parameter

**Comment by arekm** [comment]
Did you use this script or some other version?

https://raw.githubusercontent.com/TheRemote/PiBenchmarks/master/Storage.sh

**Comment by technolhodgy** [comment]
The same one, I just did a wget of that script and ran it.

**Comment by arekm** [comment]
Could you attach entire run from script with set -x added. I wonder where utf8 sneaks in despite LC_ALL=C.

**Comment by technolhodgy** [comment]
[pibenchmarks.txt](https://github.com/TheRemote/PiBenchmarks/files/13697365/pibenchmarks.txt)

**Comment by arekm** [comment]
set -x stderr output is missing.
````
bash -x Storage.sh > log.txt 2>&1
````

**Comment by technolhodgy** [comment]
I just rememberedI commented out '##set' -x lol

Here it with it back in .
[log.txt](https://github.com/TheRemote/PiBenchmarks/files/13697385/log.txt)

**Comment by technolhodgy** [comment]
It is also a hardware match for https://pibenchmarks.com/benchmark/75582/
( it the actual same Crucial drive used in the test, as i took 2 drives into work for testing with )
