### ISSUE TITLE
Results not showing on page - Pi 5

### ISSUE THREAD

**Issue by mikeyd810** [TheRemote/PiBenchmarks#35]
Running the latest updates on a Pi 5 8GB with Bookworm, was getting the UTF errors but swapped the nvme show-regs command for the nvme id-ctrl and that seems to have fixed that but no matter what else I've tried results aren't making it to the website even though it appears from the attached output it's posted successfully.  This is running with a Pineberry HatDrive Bottom and Sabrent Rocket 4 Plus NVMe M.2 drive
Attached output with set -x 

[Storage.log](https://github.com/TheRemote/PiBenchmarks/files/13762140/Storage.log)

**Comment by TheRemote** [comment]
Hey Mikey,

This was just because the model SB-RKT4P-500 wasn't recognized yet on the site.  I see now that all your submissions are showing retroactively as I've been processing any new models that haven't been posting.

Thanks for reporting it!
